from analyst_agent.core import get_configs
from mlx_lm import load, generate as gen
from mlx_lm.sample_utils import make_sampler
from pyprojroot import here
import yaml
import re
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)


@dataclass
class Output:
    """
    Container for the agent's response.

    Attributes:
        raw: Raw text generated by the language model.
        code: Extracted Python code, or None if no executable code was found.
    """
    raw: str
    code: str | None

def build_messages(question: str, no_think: bool, user_prompt: str, data_file: str, system_prompt: str, tools_prompt: str, tools: object = None) -> list[dict[str, str]]:
    """
    Construct the chat messages sent to the language model.

    Args:
        question: The user's analytical question.
        no_think: Whether to append the `/no_think` directive to the user prompt.
        user_prompt: The template used to construct the user message. It must
            contain placeholders for `data_file` and `question`.
        data_file: The path or name of the data file to include in the user prompt.
        system_prompt: The system message content.
        tools_prompt: Instructions describing the available tools, appended when
            tools are provided.
        tools: Optional tools available to the language model.

    Returns:
        A list of chat messages containing the system and user messages,
        formatted for the MLX tokenizer.
    """

    # Build the user prompt using the configured data file
    user_prompt = user_prompt.format(
        data_file=data_file,
        question=question
    )

    # Optionally append the tools rule
    if tools is not None:
        user_prompt = f"{user_prompt}\n{tools_prompt}"

    # Optionally append the /no_think directive
    if no_think:
        user_prompt = f"{user_prompt} /no_think"

    msgs = [
        {'role': 'system', 'content': system_prompt},
        {'role': 'user', 'content': user_prompt}
    ]

    return msgs


class Agent:
    """
    Wrapper around an MLX language model for generating Python code
    to answer analytical questions.

    The agent is responsible for:
    - Loading the model and tokenizer.
    - Constructing prompts.
    - Generating responses.
    - Extracting executable Python code from the model output.
    """

    def __init__(self, model, adapter_path: str | None = None):
        """
        Initialise the agent.

        Loads the specified MLX model, prompt templates and project
        configuration.
        """

        # Load MLX model and tokenizer
        self.model, self.tokenizer = load(model, adapter_path = adapter_path)

        # Load system and user prompts
        with open(here() / 'configs' / 'prompts.yaml') as f:
            prompts = yaml.safe_load(f)

        self.user_prompt = prompts['sandbox_user_prompt']
        self.system_prompt = prompts['sandbox_system_prompt']
        self.tools_prompt = prompts['tools_prompt']

        # Load project configuration
        self.configs = get_configs()

    def _build_messages(self, question: str, no_think: bool, tools: object = None) -> list[dict[str, str]]:
        return build_messages(
            question=question,
            no_think=no_think,
            user_prompt=self.user_prompt,
            data_file=self.configs['carbon_data'].name,
            system_prompt=self.system_prompt,
            tools_prompt=self.tools_prompt,
            tools=tools
        )



    def generate(self, no_think: bool, question: str | None = None, max_tokens: int = 1000, temp: float = 0.0, tools: list[dict] | None = None, messages: list[dict] | None = None) -> str:
        """
        Generate a response from the language model.

        Args:
            question: Analytical question to answer. Ignored if `messages` is provided.
            no_think: Whether to append the /no_think directive to the prompt.
            max_tokens: Maximum number of tokens the model may generate.
            temp: Sampling temperature controlling response randomness.
            tools: Optional list of tool schemas available to the model.
            messages: Optional pre-built conversation history. If provided, this is
                used directly instead of constructing a new prompt from `question`.

        Returns:
            The raw text generated by the language model.
        """

        if messages is None and question is None:
            raise ValueError('generate needs either question or messages')

        # Build a new conversation only if one has not been supplied
        if messages is None:
            messages = self._build_messages(question, no_think, tools)

        # Convert the conversation into the chat prompt expected by the tokenizer,
        # including any tools available to the model
        prompt = self.tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=False,
            tools=tools
        )

        # Create the sampling strategy using the requested temperature
        sample = make_sampler(temp=temp)

        # Generate a response from the model
        output = gen(
            model=self.model,
            tokenizer=self.tokenizer,
            max_tokens=max_tokens,
            prompt=prompt,
            sampler=sample
        )

        return output


    @staticmethod
    def extract_code(out: str) -> Output:
        """
        Extract executable Python code from a model response.

        The function removes any reasoning enclosed within </think>
        tags before attempting to extract code blocks. If no fenced
        code block is present but Python code appears to have been
        generated, the remaining text is treated as code.

        Args:
            out: Raw model output.

        Returns:
            Output containing both the raw response and extracted code.
        """

        # Remove reasoning section (if present)
        stage_1 = out.split('</think>')[-1].strip()

        # Only attempt extraction if executable code appears present
        if 'print(' in stage_1:

            # Look for fenced Python code blocks
            match = re.search(r"```[a-z]*\s*(.*?)```", stage_1, re.DOTALL)

            # If no fenced block exists, assume the remaining text is code
            if match is None:
                code = stage_1
            else:
                code = match.group(1).strip()

        else:
            logger.info('No code extracted')
            code = None

        return Output(
            raw=out,
            code=code
        )


    def answer(self, question: str, no_think: bool = True, max_tokens: int = 1000, temp: float = 0.0) -> Output:
        """
        Generate an answer and extract executable code.

        Args:
            question: User's analytical question.
            no_think: Whether to append the /no_think directive.
            max_tokens: Maximum number of tokens to generate.
            temp: Sampling temperature controlling response randomness.

        Returns:
            Output containing the raw model response and extracted code.
        """

        # Generate model response
        output = self.generate(question=question, no_think=no_think, max_tokens=max_tokens, temp=temp)

        # Extract executable code from the response
        result = Agent.extract_code(output)

        return result
        
    

    
if __name__=='__main__':
        agent = Agent("Qwen/Qwen3-1.7B")     # loads the model

        r = agent.answer("Create a neural network forecast to predict carbon data?")
        print(repr(r.raw)); print("---"); print(repr(r.code))
