from analyst_agent.core import get_configs
from mlx_lm import load, generate as gen
from pyprojroot import here
import yaml
import re
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)


@dataclass
class Output:
    """
    Container for the agent's response.

    Attributes:
        raw: Raw text generated by the language model.
        code: Extracted Python code, or None if no executable code was found.
    """
    raw: str
    code: str | None


class Agent:
    """
    Wrapper around an MLX language model for generating Python code
    to answer analytical questions.

    The agent is responsible for:
    - Loading the model and tokenizer.
    - Constructing prompts.
    - Generating responses.
    - Extracting executable Python code from the model output.
    """

    def __init__(self, model):
        """
        Initialise the agent.

        Loads the specified MLX model, prompt templates and project
        configuration.
        """

        # Load MLX model and tokenizer
        self.model, self.tokenizer = load(model)

        # Load system and user prompts
        with open(here() / 'configs' / 'prompts.yaml') as f:
            prompts = yaml.safe_load(f)

        self.user_prompt = prompts['sandbox_user_prompt']
        self.system_prompt = prompts['sandbox_system_prompt']

        # Load project configuration
        self.configs = get_configs()


    def _build_messages(self, question: str, no_think: bool) -> list[dict[str, str]]:
        """
        Construct the chat messages sent to the language model.

        Args:
            question: User's analytical question.
            no_think: Whether to append the /no_think directive.

        Returns:
            List of chat messages formatted for the MLX tokenizer.
        """

        # Build the user prompt using the configured data file
        user_prompt = self.user_prompt.format(
            data_file=self.configs['carbon_data'].name,
            question=question
        )

        # Optionally append the /no_think directive
        if no_think:
            user_prompt = f"{user_prompt} /no_think"

        msgs = [
            {'role': 'system', 'content': self.system_prompt},
            {'role': 'user', 'content': user_prompt}
        ]

        return msgs


    def generate(self, question: str, no_think: bool, max_tokens: int) -> str:
        """
        Generate a raw response from the language model.

        Args:
            question: User's analytical question.
            no_think: Whether to append the /no_think directive.
            max_tokens: Maximum number of tokens to generate.

        Returns:
            Raw text generated by the model.
        """

        # Construct conversation history
        messages = self._build_messages(question, no_think)

        # Convert messages into the model's chat format
        prompt = self.tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=False
        )

        # Generate model output
        output = gen(
            model=self.model,
            tokenizer=self.tokenizer,
            max_tokens=max_tokens,
            verbose=True,
            prompt=prompt
        )

        return output


    @staticmethod
    def extract_code(out: str) -> Output:
        """
        Extract executable Python code from a model response.

        The function removes any reasoning enclosed within </think>
        tags before attempting to extract code blocks. If no fenced
        code block is present but Python code appears to have been
        generated, the remaining text is treated as code.

        Args:
            out: Raw model output.

        Returns:
            Output containing both the raw response and extracted code.
        """

        # Remove reasoning section (if present)
        stage_1 = out.split('</think>')[-1].strip()

        # Only attempt extraction if executable code appears present
        if 'print(' in stage_1:

            # Look for fenced Python code blocks
            match = re.search("```[a-z]*\s*(.*?)```", stage_1, re.DOTALL)

            # If no fenced block exists, assume the remaining text is code
            if match is None:
                code = stage_1
            else:
                code = match.group(1).strip()

        else:
            logger.info('No code extracted')
            code = None

        return Output(
            raw=out,
            code=code
        )


    def answer(self, question: str, no_think: bool = True, max_tokens: int = 1000) -> Output:
        """
        Generate an answer and extract executable code.

        Args:
            question: User's analytical question.
            no_think: Whether to append the /no_think directive.
            max_tokens: Maximum number of tokens to generate.

        Returns:
            Output containing the raw model response and extracted code.
        """

        # Generate model response
        output = self.generate(question, no_think, max_tokens)

        # Extract executable code from the response
        result = Agent.extract_code(output)

        return result
        
    

    
if __name__=='__main__':
        agent = Agent("Qwen/Qwen3-1.7B")     # loads the model

        r = agent.answer("Create a neural network forecast to predict carbon data?")
        print(repr(r.raw)); print("---"); print(repr(r.code))
